IOP_BIN = smap.irx
IOP_OBJS = main.o smap.o xfer.o imports.o

IOP_INCS += -I../../iopcore/common -I../common

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
