IOP_BIN  = smbinit.irx
IOP_OBJS = main.o smbauth.o des.o md4.o imports.o

IOP_INCS += -I../../iopcore/common

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
