#ifndef __DIALOGS_H
#define __DIALOGS_H

#include "include/dia.h"

enum UI_ITEMS{
	UICFG_THEME		=	10,
	UICFG_LANG,
	UICFG_SCROLL,
	UICFG_BGCOL,
	UICFG_UICOL,
	UICFG_TXTCOL,
	UICFG_SELCOL,
	UICFG_AUTOSORT,
	UICFG_COVERART,
	UICFG_WIDESCREEN,
	UICFG_AUTOREFRESH,
	UICFG_VMODE,
	UICFG_INFOPAGE,

	GSCFG_ENABLEGSM,
	GSCFG_GSMVMODE,
	GSCFG_GSMXOFFSET,
	GSCFG_GSMYOFFSET,
	GSCFG_GSMSKIPVIDEOS,

	CFG_EXITTO,
	CFG_DEFDEVICE,
	CFG_DEBUG,
	CFG_USBMODE,
	CFG_HDDMODE,
	CFG_ETHMODE,
	CFG_APPMODE,
	CFG_CHECKUSBFRAG,
	CFG_LASTPLAYED,
	CFG_SHOWGSM,
	CFG_DANDROP,
	CFG_USBPREFIX,
	CFG_ETHPREFIX,
	CFG_HDDSPINDOWN,

	NETCFG_RECONNECT,
	NETCFG_OK,
	NETCFG_ETHOPMODE,

	CFG_SHOWCHEAT,
	CHEATCFG_ENABLECHEAT,
	CHEATCFG_CHEATMODE,


	COMPAT_CDVDMAN_TIMER		= 100,
	COMPAT_DMA,
	COMPAT_ALTSTARTUP,
	COMPAT_GAME,
	COMPAT_GAMEID,
	COMPAT_SAVE,
	COMPAT_TEST,
	COMPAT_REMOVE,

	COMPAT_LOADFROMDISC_ID,
#ifdef VMC
	COMPAT_VMC1_ACTION_ID,
	COMPAT_VMC2_ACTION_ID,
	COMPAT_VMC1_DEFINE_ID,
	COMPAT_VMC2_DEFINE_ID,

	VMC_NAME,
	VMC_SIZE,
	VMC_BUTTON_CREATE,
	VMC_BUTTON_DELETE,
	VMC_STATUS,
	VMC_PROGRESS,
	VMC_REFRESH,
#endif

	COMPAT_MODE_BASE		= 200,
};

#define COMPAT_NOEXIT 			0x70000000
#define COMPAT_LOADFROMDISC		(COMPAT_LOADFROMDISC_ID | COMPAT_NOEXIT)
#ifdef VMC
#define COMPAT_VMC1_ACTION		(COMPAT_VMC1_ACTION_ID | COMPAT_NOEXIT)
#define COMPAT_VMC2_ACTION		(COMPAT_VMC2_ACTION_ID | COMPAT_NOEXIT)
#define COMPAT_VMC1_DEFINE		(COMPAT_VMC1_DEFINE_ID | COMPAT_NOEXIT)
#define COMPAT_VMC2_DEFINE		(COMPAT_VMC2_DEFINE_ID | COMPAT_NOEXIT)
#endif

extern struct UIItem diaIPConfig[];
extern struct UIItem diaCompatConfig[];
extern struct UIItem diaUIConfig[];
extern struct UIItem diaGSConfig[];
extern struct UIItem diaCheatConfig[];

extern struct UIItem diaConfig[];
extern struct UIItem diaAbout[];
#ifdef VMC
extern struct UIItem diaVMC[];
#endif

#endif
