IOP_BIN  = udptty.irx
IOP_OBJS = udptty.o imports.o exports.o

IOP_INCS += -I../../network/common
IOP_CFLAGS += -DKPRTTY

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
