#include "lang_autogen.h"

// THIS FILE WAS AUTO-GENERATED.
char *internalEnglish[LANG_STR_COUNT] = {
    "English (internal)",
    "Save Changes",
    "Back",
    "Network Settings",
    "Advanced Options",
    "<no values>",
    "Settings saved to %s",
    "Error writing settings!",
    "Exit",
    "Settings",
    "Menu",
    "BDM Games",
    "HDD Games",
    "ETH Games",
    "Apps",
    "Theme",
    "Language",
    "The system will be powered off.",
    "Exit to Browser?",
    "Cancel updating?",
    "%d: HardDisk Drive not detected.",
    "%d: HardDisk Drive not formatted.",
    "%d: Network startup error.",
    "%d: No network adaptor detected.",
    "%d: Cannot connect to SMB server.",
    "%d: Cannot log into SMB server.",
    "%d: Cannot open SMB share.",
    "%d: Cannot list SMB shares.",
    "%d: Cannot list games.",
    "%d: DHCP server unavailable.",
    "%d: No network connection.",
    "On",
    "Off",
    "OK",
    "Select",
    "Cancel",
    "Circle",
    "Cross",
    "Games List",
    "Game Settings",
    "Remove Settings",
    "Scrolling Speed",
    "Slow",
    "Medium",
    "Fast",
    "Default Menu",
    "Load From Disc",
    "Please wait.",
    "Error while loading the Game ID.",
    "Automatic Sorting",
    "Error loading the language file.",
    "Debug Colors",
    "No controller detected, waiting...",
    "Cover Art",
    "Widescreen",
    "Power Off",
    "Loading config...",
    "Saving config...",
    "Start Device",
    "Refresh",
    "BDM Start Mode",
    "HDD Device Start Mode",
    "ETH Device Start Mode",
    "Applications Start Mode",
    "Auto",
    "Manual",
    "Start NBD Server",
    "NBD Server starting...",
    "NBD Server running...",
    "Failed to start NBD Server.",
    "NBD Server unloading...",
    "IGR Path",
    "Background Color",
    "Text Color",
    "- SMB Server -",
    "IP Address Type",
    "Static",
    "DHCP",
    "IP Address",
    "Address",
    "Mask",
    "Gateway",
    "DNS Server",
    "Port",
    "Share",
    "User",
    "Password",
    "<not set>",
    "Address Type",
    "IP",
    "NetBIOS",
    "Accept",
    "Item will be permanently deleted, continue?",
    "Rename",
    "Delete",
    "Run",
    "Display Settings",
    "Write Operations",
    "Remember Last Played Game",
    "Select Button",
    "Error, the game is fragmented.",
    "Error, could not run the item.",
    "Test Changes",
    "Leave empty for GUEST auth.",
    "Accurate Reads",
    "Synchronous Mode",
    "Unhook Syscalls",
    "Skip Videos",
    "Emulate DVD-DL",
    "Disable IGR",
    "Changing the size will reformat the VMC.",
    "Create",
    "Start",
    "Modify",
    "Abort",
    "Reset",
    "Use Generic",
    "Configure VMC",
    "Name",
    "Size",
    "Status",
    "Progress",
    "VMC file exists.",
    "Invalid VMC file, size is incorrect.",
    "VMC file needs to be created.",
    "Error accessing VMC %s. Continue with the Memory Card in slot %d?",
    "Automatic Refresh",
    "About",
    "Coders",
    "Quality Assurance",
    "BDM Prefix Path",
    "Boots custom ELF after an IGR.",
    "Value in minute(s), 0 to disable spin down.",
    "Automatic HDD Spin Down",
    "Video Mode",
    "Dialog Color",
    "Selected Color",
    "Reset Colors",
    "Info",
    "Custom ELF",
    "Color Selection",
    "Reconnect",
    "Leave empty to list shares.",
    "ETH Prefix Path",
    "Backspace",
    "Space",
    "Enter",
    "Mode",
    "VMC Slot 1",
    "VMC Slot 2",
    "Game ID",
    "DMA Mode",
    "V-Sync",
    "Mode 1",
    "Mode 2",
    "Mode 3",
    "Mode 4",
    "Mode 5",
    "Mode 6",
    "Configure GSM",
    "Ethernet Link Mode",
    "100Mbit Full-duplex",
    "100Mbit Half-duplex",
    "10Mbit Full-duplex",
    "10Mbit Half-duplex",
    "GSM Settings",
    "GSM Selector",
    "Toggles GSM on/off.",
    "Forced custom display mode.",
    "H-POS",
    "Horizontal adjustment.",
    "V-POS",
    "Vertical adjustment.",
    "Overscan",
    "Overscan adjustment.",
    "FMV Skip",
    "Skips full motion videos.",
    "Cheat Settings",
    "PS2RD Cheat Engine",
    "Lets PS2RD Cheat Engine patch your game.",
    "PS2RD Cheat Engine Mode",
    "Auto select or select game cheats.",
    "Auto Select Cheats",
    "Select Game Cheats",
    "Error: failed to load cheat file.",
    "No cheats found.",
    "Download Defaults",
    "Network Update",
    "Overwrite Existing Records",
    "Update failed.",
    "Failed to connect to update server.",
    "Update completed.",
    "Update cancelled.",
    "Download settings from the network?",
    "Customized Settings",
    "Downloaded Defaults",
    "Auto start in %i s...",
    "Auto Start",
    "Value in second(s), 0 to disable auto start.",
    "PS2 Logo",
    "Displayed for a valid disc logo matching the console's region.",
    "Configure PADEMU",
    "Pad Emulator Settings",
    "Pad Emulator",
    "Turns on/off Pad Emulator for selected game.",
    "Pad Emulator Mode",
    "Select Pad Emulator mode.",
    "DualShock3/4 USB",
    "DualShock3/4 BT",
    "Settings For Port:",
    "Select Pad Emulator port for settings.",
    "Emulation",
    "Turns on/off Pad Emulator for selected port.",
    "Vibration",
    "Turns on/off vibration for Pad Emulator selected port.",
    "USB Bluetooth Adapter MAC Address:",
    "DS Controller Paired To MAC Address:",
    "Pair",
    "Pair DS Controller",
    "Pair DS controller with Bluetooth adapter MAC address.",
    "Not Connected",
    "Bluetooth Adapter Information",
    "Shows more information and supported features.",
    "HCI Version:",
    "LMP Version:",
    "Manufacturer ID:",
    "Supported Features:",
    "Yes",
    "No",
    "Bluetooth adapter should be fully compatible with DS3/DS4 controllers.",
    "Bluetooth adapter may not work correctly with DS3/DS4 controllers.",
    "Multitap Emulation",
    "Turns on/off Multitap emulation for selected game.",
    "Multitap Emulator On Port:",
    "Select port for Multitap emulation.",
    "Fake DS3 Workaround",
    "Some fake DS3s need a workaround, this option will enable it.",
    "Emulate FIELD Flipping",
    "Fix for games that glitch under progressive video modes.",
    "Parental Lock Settings",
    "Parental Lock Password",
    "Leave blank to disable the parental lock.",
    "Enter Parental Lock Password",
    "Parental lock password incorrect.",
    "Parental lock disabled.",
    "Build Options:",
    "Error - this password cannot be used.",
    "VMC %s file is fragmented. Continue with Memory Card in slot %d?",
    "Audio Settings",
    "Sound Effects",
    "Boot Sound",
    "Sound Effects Volume",
    "Boot Sound Volume",
    "Confirm video mode change?",
    "Cache Game List (HDD)",
    "Notifications",
    "Config loaded from %s",
    "Theme loaded from %s",
    "Language loaded from %s",
    "%s partition mounted.",
    "Options",
    "Game settings saved.",
    "%s settings removed.",
    "Overwrites existing game compatibility settings when enabled.",
    "Settings Mode",
    "Global",
    "Per Game",
    "All",
    "Select settings to remove.",
    "Support Forums:",
    "Title",
    "Genre",
    "Release",
    "Developer",
    "Description",
    "Block Devices",
    "Controller Settings",
    "Turn on/off Block Device Manager.",
    "Turn on/off Block Devices (e.g. USB).",
    "USB Games",
    "iLink Games",
    "MX4SIO Games",
    "Configure PADMACRO",
    "Pad macro Settings",
    "Pad macros",
    "Analog slow-down:",
    "Reduce range of analog stick when button is pressed",
    "Left stick",
    "Right stick",
    "Analog axis invert:",
    "Invert analog stick axis",
    "Turbo button speed",
    "How fast to press the button when turbo is active",
    "While button pressed",
    "Toggled by button",
};
